@startuml

start

:generate intial population;

repeat 
  :order by fitness;
  :keep top 10%,\ndiscard bottom 90%;
  :replenish depleated population\nby applying cross-over\nto pairs of top 10% candidates &\nmutation to individual candidates;
repeat while (10 min have not passed)
:return most fit;
stop

@enduml
