@startuml

start

:generate intial population;

repeat 
  :decrease p(cross-over);
  :increase p(mutation);
  :order candidates by fitness;
  :keep a fraction of the\npopulation with the highest fittness\ndiscard the rest;
  :replenish depleated population\nby applying cross-over\nto pairs of top candidates &\nmutation to individual candidates;
repeat while (enough time has not passed)
:return most fit;
stop

@enduml
